source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'
pod 'SDCycleScrollView', '~> 1.61'
pod 'ReactiveCocoa', '2.3.1'
pod 'EAIntroView', '~> 2.8.0'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MMDrawerController', '~> 0.5.7'
pod 'BlocksKit', '2.2.5'